import { Inter } from "next/font/google";
import "./globals.css";
import LoginBtn from './LoginBtn' 
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  let session = await getServerSession(authOptions)
  //console.log(session.user.name)
  return (
    <html lang="en">
      
      <body className={inter.className}>
        {
          session==null?<LoginBtn/>  : session.user.name
        }
      
        {children}</body>
    </html>
  );
}
